// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/fs.proto

package filesystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =========================
// ENUM
// =========================
type FileMode int32

const (
	FileMode_READ  FileMode = 0
	FileMode_WRITE FileMode = 1
)

// Enum value maps for FileMode.
var (
	FileMode_name = map[int32]string{
		0: "READ",
		1: "WRITE",
	}
	FileMode_value = map[string]int32{
		"READ":  0,
		"WRITE": 1,
	}
)

func (x FileMode) Enum() *FileMode {
	p := new(FileMode)
	*p = x
	return p
}

func (x FileMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fs_proto_enumTypes[0].Descriptor()
}

func (FileMode) Type() protoreflect.EnumType {
	return &file_proto_fs_proto_enumTypes[0]
}

func (x FileMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileMode.Descriptor instead.
func (FileMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_fs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{0}
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mode          FileMode               `protobuf:"varint,3,opt,name=mode,proto3,enum=filesystem.FileMode" json:"mode,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=clientId,proto3" json:"clientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_fs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{1}
}

func (x *FileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRequest) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_READ
}

func (x *FileRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Mode          FileMode               `protobuf:"varint,4,opt,name=mode,proto3,enum=filesystem.FileMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_fs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateRequest) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_READ
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_fs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Fd            int32                  `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Dirty         bool                   `protobuf:"varint,3,opt,name=dirty,proto3" json:"dirty,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_fs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{4}
}

func (x *CloseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CloseRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *CloseRequest) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *CloseRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CloseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Fd            int32                  `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Dirty         bool                   `protobuf:"varint,3,opt,name=dirty,proto3" json:"dirty,omitempty"`
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_fs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{5}
}

func (x *WriteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *WriteRequest) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *WriteRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Fd            int32                  `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_fs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ReadRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

type TestAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAuthRequest) Reset() {
	*x = TestAuthRequest{}
	mi := &file_proto_fs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAuthRequest) ProtoMessage() {}

func (x *TestAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAuthRequest.ProtoReflect.Descriptor instead.
func (*TestAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{7}
}

func (x *TestAuthRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// =========================
// RESPONSES
// =========================
type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_fs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{8}
}

func (x *OpenResponse) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *OpenResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OpenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_fs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{9}
}

func (x *CloseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CloseResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_fs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_fs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{11}
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WriteResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_fs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{12}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAuthResponse) Reset() {
	*x = TestAuthResponse{}
	mi := &file_proto_fs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAuthResponse) ProtoMessage() {}

func (x *TestAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAuthResponse.ProtoReflect.Descriptor instead.
func (*TestAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{13}
}

func (x *TestAuthResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type LeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderResponse) Reset() {
	*x = LeaderResponse{}
	mi := &file_proto_fs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderResponse) ProtoMessage() {}

func (x *LeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderResponse.ProtoReflect.Descriptor instead.
func (*LeaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{14}
}

func (x *LeaderResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *LeaderResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_fs_proto protoreflect.FileDescriptor

const file_proto_fs_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/fs.proto\x12\n" +
	"filesystem\x1a\x1bgoogle/protobuf/empty.proto\"\a\n" +
	"\x05Empty\"\x8e\x01\n" +
	"\vFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.filesystem.FileModeR\x04mode\x12\x1a\n" +
	"\bclientId\x18\x04 \x01(\tR\bclientId\"\x90\x01\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bclientId\x18\x03 \x01(\tR\bclientId\x12(\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x14.filesystem.FileModeR\x04mode\"J\n" +
	"\rDeleteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\"\x81\x01\n" +
	"\fCloseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x05R\x02fd\x12\x14\n" +
	"\x05dirty\x18\x03 \x01(\bR\x05dirty\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"\x81\x01\n" +
	"\fWriteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x05R\x02fd\x12\x14\n" +
	"\x05dirty\x18\x03 \x01(\bR\x05dirty\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"9\n" +
	"\vReadRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x05R\x02fd\"-\n" +
	"\x0fTestAuthRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"R\n" +
	"\fOpenResponse\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"C\n" +
	"\rCloseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\rWriteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"\"\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\",\n" +
	"\x10TestAuthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\"G\n" +
	"\x0eLeaderResponse\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\tR\bleaderId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress*\x1f\n" +
	"\bFileMode\x12\b\n" +
	"\x04READ\x10\x00\x12\t\n" +
	"\x05WRITE\x10\x012\x89\x04\n" +
	"\vFileService\x129\n" +
	"\x04Open\x12\x17.filesystem.FileRequest\x1a\x18.filesystem.OpenResponse\x12=\n" +
	"\x06Create\x12\x19.filesystem.CreateRequest\x1a\x18.filesystem.OpenResponse\x12<\n" +
	"\x05Close\x12\x18.filesystem.CloseRequest\x1a\x19.filesystem.CloseResponse\x12?\n" +
	"\x06Delete\x12\x19.filesystem.DeleteRequest\x1a\x1a.filesystem.DeleteResponse\x12<\n" +
	"\x05Write\x12\x18.filesystem.WriteRequest\x1a\x19.filesystem.WriteResponse\x12;\n" +
	"\x04Read\x12\x17.filesystem.ReadRequest\x1a\x18.filesystem.ReadResponse0\x01\x12E\n" +
	"\bTestAuth\x12\x1b.filesystem.TestAuthRequest\x1a\x1c.filesystem.TestAuthResponse\x12?\n" +
	"\tGetLeader\x12\x16.google.protobuf.Empty\x1a\x1a.filesystem.LeaderResponseB\rZ\v/filesystemb\x06proto3"

var (
	file_proto_fs_proto_rawDescOnce sync.Once
	file_proto_fs_proto_rawDescData []byte
)

func file_proto_fs_proto_rawDescGZIP() []byte {
	file_proto_fs_proto_rawDescOnce.Do(func() {
		file_proto_fs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fs_proto_rawDesc), len(file_proto_fs_proto_rawDesc)))
	})
	return file_proto_fs_proto_rawDescData
}

var file_proto_fs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_fs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_fs_proto_goTypes = []any{
	(FileMode)(0),            // 0: filesystem.FileMode
	(*Empty)(nil),            // 1: filesystem.Empty
	(*FileRequest)(nil),      // 2: filesystem.FileRequest
	(*CreateRequest)(nil),    // 3: filesystem.CreateRequest
	(*DeleteRequest)(nil),    // 4: filesystem.DeleteRequest
	(*CloseRequest)(nil),     // 5: filesystem.CloseRequest
	(*WriteRequest)(nil),     // 6: filesystem.WriteRequest
	(*ReadRequest)(nil),      // 7: filesystem.ReadRequest
	(*TestAuthRequest)(nil),  // 8: filesystem.TestAuthRequest
	(*OpenResponse)(nil),     // 9: filesystem.OpenResponse
	(*CloseResponse)(nil),    // 10: filesystem.CloseResponse
	(*DeleteResponse)(nil),   // 11: filesystem.DeleteResponse
	(*WriteResponse)(nil),    // 12: filesystem.WriteResponse
	(*ReadResponse)(nil),     // 13: filesystem.ReadResponse
	(*TestAuthResponse)(nil), // 14: filesystem.TestAuthResponse
	(*LeaderResponse)(nil),   // 15: filesystem.LeaderResponse
	(*emptypb.Empty)(nil),    // 16: google.protobuf.Empty
}
var file_proto_fs_proto_depIdxs = []int32{
	0,  // 0: filesystem.FileRequest.mode:type_name -> filesystem.FileMode
	0,  // 1: filesystem.CreateRequest.mode:type_name -> filesystem.FileMode
	2,  // 2: filesystem.FileService.Open:input_type -> filesystem.FileRequest
	3,  // 3: filesystem.FileService.Create:input_type -> filesystem.CreateRequest
	5,  // 4: filesystem.FileService.Close:input_type -> filesystem.CloseRequest
	4,  // 5: filesystem.FileService.Delete:input_type -> filesystem.DeleteRequest
	6,  // 6: filesystem.FileService.Write:input_type -> filesystem.WriteRequest
	7,  // 7: filesystem.FileService.Read:input_type -> filesystem.ReadRequest
	8,  // 8: filesystem.FileService.TestAuth:input_type -> filesystem.TestAuthRequest
	16, // 9: filesystem.FileService.GetLeader:input_type -> google.protobuf.Empty
	9,  // 10: filesystem.FileService.Open:output_type -> filesystem.OpenResponse
	9,  // 11: filesystem.FileService.Create:output_type -> filesystem.OpenResponse
	10, // 12: filesystem.FileService.Close:output_type -> filesystem.CloseResponse
	11, // 13: filesystem.FileService.Delete:output_type -> filesystem.DeleteResponse
	12, // 14: filesystem.FileService.Write:output_type -> filesystem.WriteResponse
	13, // 15: filesystem.FileService.Read:output_type -> filesystem.ReadResponse
	14, // 16: filesystem.FileService.TestAuth:output_type -> filesystem.TestAuthResponse
	15, // 17: filesystem.FileService.GetLeader:output_type -> filesystem.LeaderResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_fs_proto_init() }
func file_proto_fs_proto_init() {
	if File_proto_fs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fs_proto_rawDesc), len(file_proto_fs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fs_proto_goTypes,
		DependencyIndexes: file_proto_fs_proto_depIdxs,
		EnumInfos:         file_proto_fs_proto_enumTypes,
		MessageInfos:      file_proto_fs_proto_msgTypes,
	}.Build()
	File_proto_fs_proto = out.File
	file_proto_fs_proto_goTypes = nil
	file_proto_fs_proto_depIdxs = nil
}
