// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/rep.proto

package filesystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryRequest) Reset() {
	*x = RecoveryRequest{}
	mi := &file_proto_rep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryRequest) ProtoMessage() {}

func (x *RecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryRequest.ProtoReflect.Descriptor instead.
func (*RecoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{0}
}

func (x *RecoveryRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type Replication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replication) Reset() {
	*x = Replication{}
	mi := &file_proto_rep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replication) ProtoMessage() {}

func (x *Replication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replication.ProtoReflect.Descriptor instead.
func (*Replication) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{1}
}

func (x *Replication) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Replication) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Replication) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_rep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *LogEntry) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *LogEntry) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *LogEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFullSync    bool                   `protobuf:"varint,1,opt,name=isFullSync,proto3" json:"isFullSync,omitempty"`
	LogEntries    []*LogEntry            `protobuf:"bytes,2,rep,name=logEntries,proto3" json:"logEntries,omitempty"`
	FullFiles     []*Replication         `protobuf:"bytes,3,rep,name=fullFiles,proto3" json:"fullFiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	mi := &file_proto_rep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMessage) GetIsFullSync() bool {
	if x != nil {
		return x.IsFullSync
	}
	return false
}

func (x *UpdateMessage) GetLogEntries() []*LogEntry {
	if x != nil {
		return x.LogEntries
	}
	return nil
}

func (x *UpdateMessage) GetFullFiles() []*Replication {
	if x != nil {
		return x.FullFiles
	}
	return nil
}

// -------- Heartbeat --------
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryId     string                 `protobuf:"bytes,1,opt,name=primaryId,proto3" json:"primaryId,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_rep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetPrimaryId() string {
	if x != nil {
		return x.PrimaryId
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_rep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// -------- AppendEntries --------
type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      string                 `protobuf:"bytes,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int32                  `protobuf:"varint,3,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"` //highest log index that is replicated by majority
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_proto_rep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{6}
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int32 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_proto_rep_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rep_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rep_proto_rawDescGZIP(), []int{7}
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_rep_proto protoreflect.FileDescriptor

const file_proto_rep_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/rep.proto\x12\x02pb\"-\n" +
	"\x0fRecoveryRequest\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\"]\n" +
	"\vReplication\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\x80\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\"\x8c\x01\n" +
	"\rUpdateMessage\x12\x1e\n" +
	"\n" +
	"isFullSync\x18\x01 \x01(\bR\n" +
	"isFullSync\x12,\n" +
	"\n" +
	"logEntries\x18\x02 \x03(\v2\f.pb.LogEntryR\n" +
	"logEntries\x12-\n" +
	"\tfullFiles\x18\x03 \x03(\v2\x0f.pb.ReplicationR\tfullFiles\"G\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\tprimaryId\x18\x01 \x01(\tR\tprimaryId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"~\n" +
	"\x14AppendEntriesRequest\x12\x1a\n" +
	"\bleaderId\x18\x01 \x01(\tR\bleaderId\x12&\n" +
	"\aentries\x18\x02 \x03(\v2\f.pb.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x03 \x01(\x05R\fleaderCommit\"1\n" +
	"\x15AppendEntriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Z\n" +
	"\x12ReplicationService\x12D\n" +
	"\rAppendEntries\x12\x18.pb.AppendEntriesRequest\x1a\x19.pb.AppendEntriesResponse2L\n" +
	"\x0fRecoveryService\x129\n" +
	"\x0fRequestRecovery\x12\x13.pb.RecoveryRequest\x1a\x11.pb.UpdateMessage2I\n" +
	"\x10HeartbeatService\x125\n" +
	"\rSendHeartbeat\x12\r.pb.Heartbeat\x1a\x15.pb.HeartbeatResponseB\rZ\v/filesystemb\x06proto3"

var (
	file_proto_rep_proto_rawDescOnce sync.Once
	file_proto_rep_proto_rawDescData []byte
)

func file_proto_rep_proto_rawDescGZIP() []byte {
	file_proto_rep_proto_rawDescOnce.Do(func() {
		file_proto_rep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rep_proto_rawDesc), len(file_proto_rep_proto_rawDesc)))
	})
	return file_proto_rep_proto_rawDescData
}

var file_proto_rep_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_rep_proto_goTypes = []any{
	(*RecoveryRequest)(nil),       // 0: pb.RecoveryRequest
	(*Replication)(nil),           // 1: pb.Replication
	(*LogEntry)(nil),              // 2: pb.LogEntry
	(*UpdateMessage)(nil),         // 3: pb.UpdateMessage
	(*Heartbeat)(nil),             // 4: pb.Heartbeat
	(*HeartbeatResponse)(nil),     // 5: pb.HeartbeatResponse
	(*AppendEntriesRequest)(nil),  // 6: pb.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 7: pb.AppendEntriesResponse
}
var file_proto_rep_proto_depIdxs = []int32{
	2, // 0: pb.UpdateMessage.logEntries:type_name -> pb.LogEntry
	1, // 1: pb.UpdateMessage.fullFiles:type_name -> pb.Replication
	2, // 2: pb.AppendEntriesRequest.entries:type_name -> pb.LogEntry
	6, // 3: pb.ReplicationService.AppendEntries:input_type -> pb.AppendEntriesRequest
	0, // 4: pb.RecoveryService.RequestRecovery:input_type -> pb.RecoveryRequest
	4, // 5: pb.HeartbeatService.SendHeartbeat:input_type -> pb.Heartbeat
	7, // 6: pb.ReplicationService.AppendEntries:output_type -> pb.AppendEntriesResponse
	3, // 7: pb.RecoveryService.RequestRecovery:output_type -> pb.UpdateMessage
	5, // 8: pb.HeartbeatService.SendHeartbeat:output_type -> pb.HeartbeatResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_rep_proto_init() }
func file_proto_rep_proto_init() {
	if File_proto_rep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rep_proto_rawDesc), len(file_proto_rep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_rep_proto_goTypes,
		DependencyIndexes: file_proto_rep_proto_depIdxs,
		MessageInfos:      file_proto_rep_proto_msgTypes,
	}.Build()
	File_proto_rep_proto = out.File
	file_proto_rep_proto_goTypes = nil
	file_proto_rep_proto_depIdxs = nil
}
