syntax = "proto3";

package filesystem;

option go_package = "/filesystem";

import "google/protobuf/empty.proto";

// =========================
// ENUM
// =========================
enum FileMode {
    READ = 0;
    WRITE = 1;
}

// =========================
// REQUESTS
// =========================

message Empty {}

message FileRequest {
    string request_id = 1;
    string filename   = 2;
    FileMode mode     = 3;
    string clientId = 4;
}

message CreateRequest {
    string request_id = 1;
    string filename   = 2;
    string clientId = 3;
    FileMode mode = 4;
}

message DeleteRequest {
    string request_id = 1;
    string filename   = 2;
}

message CloseRequest {
    string request_id = 1;
    int32 fd          = 2;
    bool dirty        = 3;
    int32 version     = 4;
    bytes data        = 5;
}

message WriteRequest {
    string request_id = 1;
    int32 fd          = 2;
    bool dirty        = 3;
    int32 version     = 4;
    bytes data        = 5;
}

message ReadRequest {
    string filename  = 1;
    int32 fd = 2;
}

message TestAuthRequest {
    string filename = 1;
}


// =========================
// RESPONSES
// =========================
message OpenResponse {
    int32 fd        = 1;
    int32 version   = 2;
    string message  = 3;
}

message CloseResponse {
    string message = 1;
    int32 version  = 2;
}

message DeleteResponse {
    string message = 1;
}

message WriteResponse {
    string message = 1;
    int32 version  = 2;
}

message ReadResponse {
    bytes data      = 1;
}

message TestAuthResponse {
    int32 version = 1;
}

message LeaderResponse {
  string leader_id = 1;
  string address = 2;
}


// =========================
// SERVICE
// =========================
service FileService {

    // Open file (read or write)
    rpc Open(FileRequest) returns (OpenResponse);

    // Create new file (always write mode)
    rpc Create(CreateRequest) returns (OpenResponse);

    // Close file (commit changes if dirty)
    rpc Close(CloseRequest) returns (CloseResponse);
    // Delete file
    rpc Delete(DeleteRequest) returns (DeleteResponse);

    // Write file
    rpc Write(WriteRequest) returns (WriteResponse);

    // Read file
    rpc Read(ReadRequest) returns (stream ReadResponse);

    // test if file in client cache is up to date
    rpc TestAuth(TestAuthRequest) returns (TestAuthResponse);

    rpc GetLeader(google.protobuf.Empty) returns (LeaderResponse);
}
