// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/fs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to open or create a file
type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_fs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Response for open/create
type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_fs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *OpenResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *OpenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to read
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_fs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{2}
}

func (x *ReadRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

// Response containing file data
type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_fs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{3}
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request to write
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_fs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Write response
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int32                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_fs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{5}
}

func (x *WriteResponse) GetBytesWritten() int32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// Close request
type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Dirty         bool                   `protobuf:"varint,3,opt,name=dirty,proto3" json:"dirty,omitempty"` //To check whether the file is modified or not
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_fs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{6}
}

func (x *CloseRequest) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *CloseRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CloseRequest) GetDirty() bool {
	if x != nil {
		return x.Dirty
	}
	return false
}

func (x *CloseRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Close response
type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` //New version is returned by server so client can update its cache file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_fs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{7}
}

func (x *CloseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CloseResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Delete request
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_fs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` //can use bool success also
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_fs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_fs_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_fs_proto protoreflect.FileDescriptor

const file_proto_fs_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/fs.proto\x12\n" +
	"filesystem\")\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"R\n" +
	"\fOpenResponse\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x1d\n" +
	"\vReadRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\"\"\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"2\n" +
	"\fWriteRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"4\n" +
	"\rWriteResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x05R\fbytesWritten\"b\n" +
	"\fCloseRequest\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x14\n" +
	"\x05dirty\x18\x03 \x01(\bR\x05dirty\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"C\n" +
	"\rCloseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"+\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xfd\x02\n" +
	"\vFileService\x129\n" +
	"\x04Open\x12\x17.filesystem.FileRequest\x1a\x18.filesystem.OpenResponse\x12;\n" +
	"\x06Create\x12\x17.filesystem.FileRequest\x1a\x18.filesystem.OpenResponse\x129\n" +
	"\x04Read\x12\x17.filesystem.ReadRequest\x1a\x18.filesystem.ReadResponse\x12<\n" +
	"\x05Write\x12\x18.filesystem.WriteRequest\x1a\x19.filesystem.WriteResponse\x12<\n" +
	"\x05Close\x12\x18.filesystem.CloseRequest\x1a\x19.filesystem.CloseResponse\x12?\n" +
	"\x06Delete\x12\x19.filesystem.DeleteRequest\x1a\x1a.filesystem.DeleteResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_fs_proto_rawDescOnce sync.Once
	file_proto_fs_proto_rawDescData []byte
)

func file_proto_fs_proto_rawDescGZIP() []byte {
	file_proto_fs_proto_rawDescOnce.Do(func() {
		file_proto_fs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fs_proto_rawDesc), len(file_proto_fs_proto_rawDesc)))
	})
	return file_proto_fs_proto_rawDescData
}

var file_proto_fs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_fs_proto_goTypes = []any{
	(*FileRequest)(nil),    // 0: filesystem.FileRequest
	(*OpenResponse)(nil),   // 1: filesystem.OpenResponse
	(*ReadRequest)(nil),    // 2: filesystem.ReadRequest
	(*ReadResponse)(nil),   // 3: filesystem.ReadResponse
	(*WriteRequest)(nil),   // 4: filesystem.WriteRequest
	(*WriteResponse)(nil),  // 5: filesystem.WriteResponse
	(*CloseRequest)(nil),   // 6: filesystem.CloseRequest
	(*CloseResponse)(nil),  // 7: filesystem.CloseResponse
	(*DeleteRequest)(nil),  // 8: filesystem.DeleteRequest
	(*DeleteResponse)(nil), // 9: filesystem.DeleteResponse
}
var file_proto_fs_proto_depIdxs = []int32{
	0, // 0: filesystem.FileService.Open:input_type -> filesystem.FileRequest
	0, // 1: filesystem.FileService.Create:input_type -> filesystem.FileRequest
	2, // 2: filesystem.FileService.Read:input_type -> filesystem.ReadRequest
	4, // 3: filesystem.FileService.Write:input_type -> filesystem.WriteRequest
	6, // 4: filesystem.FileService.Close:input_type -> filesystem.CloseRequest
	8, // 5: filesystem.FileService.Delete:input_type -> filesystem.DeleteRequest
	1, // 6: filesystem.FileService.Open:output_type -> filesystem.OpenResponse
	1, // 7: filesystem.FileService.Create:output_type -> filesystem.OpenResponse
	3, // 8: filesystem.FileService.Read:output_type -> filesystem.ReadResponse
	5, // 9: filesystem.FileService.Write:output_type -> filesystem.WriteResponse
	7, // 10: filesystem.FileService.Close:output_type -> filesystem.CloseResponse
	9, // 11: filesystem.FileService.Delete:output_type -> filesystem.DeleteResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fs_proto_init() }
func file_proto_fs_proto_init() {
	if File_proto_fs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fs_proto_rawDesc), len(file_proto_fs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fs_proto_goTypes,
		DependencyIndexes: file_proto_fs_proto_depIdxs,
		MessageInfos:      file_proto_fs_proto_msgTypes,
	}.Build()
	File_proto_fs_proto = out.File
	file_proto_fs_proto_goTypes = nil
	file_proto_fs_proto_depIdxs = nil
}
