syntax = "proto3";

package filesystem;

option go_package = "./proto";

// Request to open or create a file
message FileRequest {
  string filename = 1;
}

// Response for open/create
message OpenResponse {
  int32 fd = 1;
  int32 version = 2;
  string message = 3;
}

// Request to read
message ReadRequest {
  int32 fd = 1;
}

// Response containing file data
message ReadResponse {
  bytes data = 1;
}

// Request to write
message WriteRequest {
  int32 fd = 1;
  bytes data = 2;
}

// Write response
message WriteResponse {
  int32 bytes_written = 1;
}

// Close request
message CloseRequest {
  int32 fd = 1;
  int32 version = 2;
  bool dirty = 3; //To check whether the file is modified or not
  bytes data = 4;
}

// Close response
message CloseResponse {
  string message = 1;
  int32 version = 2; //New version is returned by server so client can update its cache file
}

// Delete request
message DeleteRequest {
  string filename = 1;
}

message DeleteResponse {
  string message = 1; //can use bool success also
}

service FileService {

  rpc Open(FileRequest) returns (OpenResponse);
  rpc Create(FileRequest) returns (OpenResponse);
  rpc Read(ReadRequest) returns (ReadResponse);
  rpc Write(WriteRequest) returns (WriteResponse);
  rpc Close(CloseRequest) returns (CloseResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);

}